slam_toolbox:
  ros__parameters:
    use_sim_time: true
    mode: mapping
    scan_topic: /scan
    odom_frame: odom
    base_frame: base_link
    map_frame: map
    resolution: 0.05
    max_laser_range: 3.5
    minimum_time_interval: 0.5
    transform_timeout: 0.3
    map_update_interval: 2.0
    map_start_pose: [0.0, 0.0, 0.0]
    publish_map: true
    map_publish_period: 1.0
    use_scan_matching: true
    use_imu: false
